var iconAttrs = {
search: {"search": {'scale':'.5,.5'}},
help: {"?": {}},
log:{"log": {}},
tick:{"check": {}},
greenTick:{"check": {}},
tickTrey:{"checkEnclosed": {'fill':'#f2f2f2'}},
pencil:{"pen": {'scale':'.5,.5'}},
"delete":{"minus": {}},
error:{"error": {'scale':'1.1,1.1','fill':'#B53C29','stroke-linecap':'square'}},
arrowDown:{"arrow": {'scale':'.5,.5', 'rotate':'90'}},
remove:{"close": {'scale':'.75,.75'}},
removeModal:{"close": {}},
lock:{"lock": {}},
emailForm:{"email": {}},
timeWarning:{"clock": {}},
whiteError:{"error": {'fill':'#fff', 'stroke':'#ccc', 'stroke-width':'.5'}},
lightWrench:{"wrench": {'scale':'.4,.4','fill':AD.palette.highlight}},
lightGear:{"gear": {'scale':'.75,.75','fill':AD.palette.highlight}},
lightUser:{"user": {'scale':'.35, .4','fill':AD.palette.highlight}},
lightSupport:{"lifesaver": {'scale':'.75,.75',fill:AD.palette.highlight}},
arrowLeft:{"arrowleftalt": {'scale':'.75, .75',hover:{fill:AD.palette.mid}}},
arrowRight:{"arrowalt": {'scale':'.75,.75',hover:{fill:AD.palette.mid}}},
simpleArrowLeft:{"arrowleft": {'scale':'.5,.5',hover:{fill:AD.palette.mid}}},
simpleArrowRight:{"arrow": {'scale':'.5,.5',hover:{fill:AD.palette.mid}}},
addGrey:{"add": {'scale':'1.2,1.2', 'fill':'#f2f2f2'}},
deleteGrey:{"no": {'scale':'.75,.75', 'fill':'#f2f2f2'}},
screenshots:{"screenshot": {'scale':'1.2,1.2','fill':AD.palette.mid}},
playarrow:{"playArrow": {'fill':AD.palette.mid}},
wrench:{"wrench": {'scale':'.5,.5'}},
clock:{"clock": {}},
edit:{"pen": {'scale':'.5,.5'}},
add:{"add": {}},
whitePlus:{"plusSimple": {'scale':'.7,.7'}},
whiteRemove:{"minusSimple": {'scale':'.7,.7'}},
whiteRefresh:{"refresh": {}},
whiteUndo:{"undo": {}},
toggleList:{"listView": {'scale':'1.2,1.2'}},
toggleGrid:{"gridView": {'scale':'1.2,1.2'}},
listingToggleList:{"listView": {}},
listingToggleGrid:{"gridView": {}}
};
